baseURL = 'https://0898484311.github.io/blog-hugo/'
languageCode = "vi-vn"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"

# Hai dòng này cực kỳ quan trọng để sửa lỗi ảnh ở trang con
canonifyURLs = true
relativeURLs = true

enableRobotsTXT = true
enableGitInfo = false

[pagination]
pagerSize = 3

[params]
mainSections = ["posts"]
env = "production"
# Đường dẫn ảnh phải có dấu / ở đầu
images = ["/images/og-image.png"]
ShowReadingTime = true
ShowCodeCopyButtons = true
showtoc = true

[params.profileMode]
enabled = true
name = "SINH VIÊN CNTT"
quote = "Build yourself quietly,<br>and let your success speak for you."
# Phải có dấu / ở đầu đường dẫn
imageUrl = "/images/profile.jpg"
imageWidth = 150
imageHeight = 150

[[menu.main]]
name = "Trang chủ"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "posts"
weight = 2

[[menu.main]]
name = "Giới thiệu"
url = "about"
weight = 3
